services:
  - type: web
    name: roblox-oauth
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/app.py"  # Adjust path if app.py is inside a folder
    envVars:
      - key: ROBUX_OAUTH_CLIENT_ID
        value: "6734083560814458935"
      - key: ROBUX_OAUTH_CLIENT_SECRET
        value: "RBX-7ZOWmqVYpkCKs7mHDrcBFn7mvK24kF7KYzwrZvToprwX5IPLk3uyTSgZJ7eYQeBq"
      - key: REDIRECT_URI
        value: "https://roblox-oauth-zx1j.onrender.com/auth/roblox/callback"
