services:
  - type: web
    name: roblox-oauth
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ROBUX_OAUTH_CLIENT_ID
        value: "6734083560814458935"
      - key: ROBUX_OAUTH_CLIENT_SECRET
        value: "RBX-7ZOWmqVYpkCKs7mHDrcBFn7mvK24kF7KYzwrZvToprwX5IPLk3uyTSgZJ7eYQeBq"
      - key: REDIRECT_URI
        value: "http://your-deployed-app.on.render.com/auth/roblox/callback"
